### ISSUE TITLE
Typescript compile error

### ISSUE THREAD

**Issue by mehdy-karimpour** [sanishkr/react-progressive-graceful-image#5]
Hi Sanish,

I want to use react-progressive-graceful-image in my React Typescript project, but I have a compile error for `index.d.ts` file. 
it is related to `ProgressiveImageProps` => `threshold?: Array; `

Error TS2314 Build:Generic type 'Array<T>' requires 1 type argument(s). progressive-graceful-image\src\index.d.ts 14 Build

![image](https://user-images.githubusercontent.com/75680087/168530446-755c0990-fcac-4c6d-892f-e006be3bc23a.png)

Looks should be `threshold?: Array<number>;`

Would you please consider fixing it?

best regards, mehdy

**Comment by sanishkr** [comment]
@mehdy-karimpour, Please provide a sandbox link or steps to reproduce the error.
PR is welcome as well.

PS: At first look, it might go away if you adjust your TS linter/compilation rules.

**Comment by mehdy-karimpour** [comment]
@sanishkr Array is a generic type in TS, `Array<T>`, so I think changing TS linter/compilation rules is not a good idea.
What kind of values we can pass to threshold? 
In the component description table we have [0] for it as an example. 
So it could be `Array<number>` or maybe `Array<any>`.

**Comment by sanishkr** [comment]
@mehdy-karimpour, if you are sure of it, please send a PR, I'll take a look.

**Comment by sanishkr** [comment]
@mehdy-karimpour, Can you please send a PR, I'll take a look.

**Comment by sanishkr** [comment]
`v0.7.0` should fix this.
